// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	libqdconfig "sylr.dev/libqd/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(InternalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GoModules != nil {
		in, out := &in.GoModules, &out.GoModules
		*out = make([]GoModule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyConfig is an autogenerated deepcopy function, copying the receiver, creating a new libqdconfig.Config.
func (in *Config) DeepCopyConfig() libqdconfig.Config {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoModule) DeepCopyInto(out *GoModule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoModule.
func (in *GoModule) DeepCopy() *GoModule {
	if in == nil {
		return nil
	}
	out := new(GoModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalConfig) DeepCopyInto(out *InternalConfig) {
	*out = *in
	if in.TrustedSubnets != nil {
		in, out := &in.TrustedSubnets, &out.TrustedSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalConfig.
func (in *InternalConfig) DeepCopy() *InternalConfig {
	if in == nil {
		return nil
	}
	out := new(InternalConfig)
	in.DeepCopyInto(out)
	return out
}
