name: Docker
on:
  push:
    branches: [master]
  pull_request:
jobs:
  # build job
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.16rc1"]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to GitHub Docker registry
      run: docker login ghcr.io --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Build scratch based multi-arch docker image
      run: |
        make docker-build \
          DOCKER_BUILD_GO_VERSION=${{ matrix.go }} \
          DOCKER_BUILD_IMAGE=ghcr.io/sylr/prometheus-azure-exporter-dev \
          DOCKER_BUILD_VERSION=$(git describe --always --tags --dirty --broken)-go${{ matrix.go }}
